# Generated by Django 5.0.7 on 2024-08-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_follow'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='follow',
            options={'ordering': ('-created_at',)},
        ),
    ]
